### ISSUE TITLE
Warning: Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by amitpdev** [zdying/react-native-actionsheet-api#2]
This warning happens on Android, and is freezing the UI, so its quite critical.

I have ActionSheet on two places in my app:
1. Disposable screen
2. Non disposable screen (via TabBar)

### To reproduce:
Open screen 1.
Click button to open ActionSheet on screen 1. -> Cancel.
Close screen 1.
Click button to Open ActionSheet on screen 2.

### It will throw this warning:

```
05-29 09:48:36.428  9999 10042 W ReactNativeJS: Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
05-29 09:48:36.428  9999 10042 W ReactNativeJS:
05-29 09:48:36.428  9999 10042 W ReactNativeJS: Please check the code for the ActionSheet component.
```

**Comment by zdying** [comment]
Can you provide an example of how you can reproduce this scene?

**Comment by amitpdev** [comment]
https://drive.google.com/open?id=0B5SdW7LHL9pebjVXZnhHeUU0ODQ

**Comment by zdying** [comment]
@scotbond 

Thank you for providing an example.

In fact, you **only need to initialize the ActionSheet once**, so you can directly remove the ProfileScreen in the 16th and 47th line of code.

```
16	- import ActionSheet from 'react-native-actionsheet-api'
16	+ // import ActionSheet from 'react-native-actionsheet-api'
```

```
47	-  <ActionSheet />
47	+ {/*<ActionSheet />*/}
```

After the modification, the warning will not appear.

:)

**Comment by amitpdev** [comment]
Yes its working, weird, I'm sure i've tried it. 
Thanks, please update README with this instruction.

**Comment by zdying** [comment]
@scotbond 

The README has been updated, but the Chinese version. if you like, you can help write an English version of the document 😄
